# Generated by Django 5.1 on 2024-08-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='imagens_perfil/')),
                ('nome', models.CharField(max_length=200)),
                ('data_criacao', models.DateField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=300)),
                ('quant_pets', models.PositiveIntegerField()),
                ('link_doacao', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('historia', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='imagens_perfil/')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=15)),
                ('email_tutor', models.EmailField(max_length=254, unique=True)),
                ('senha_tutor', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='imagens_perfil/')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.PositiveIntegerField()),
                ('data_ong', models.DateField()),
                ('raca', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=100)),
                ('pelagem', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('historia', models.TextField()),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='faund_app.ong')),
            ],
        ),
    ]
