# Generated by Django 5.1 on 2024-09-02 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ong',
            old_name='email',
            new_name='email_ong',
        ),
        migrations.RenameField(
            model_name='ong',
            old_name='nome',
            new_name='nome_ong',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='nome',
            new_name='nome_tutor',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='senha_tutor',
        ),
        migrations.AddField(
            model_name='ong',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
