# Generated by Django 5.1 on 2024-10-01 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0003_ong_senha_ong_tutor_senha_tutor_alter_ong_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='quant_pets',
        ),
    ]
