# Generated by Django 5.1 on 2024-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0006_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=50),
        ),
    ]
