# Generated by Django 5.1 on 2024-10-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0007_alter_ong_telefone_alter_tutor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
