# Generated by Django 5.1 on 2024-10-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0008_alter_ong_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
