# Generated by Django 5.1 on 2024-11-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0009_alter_tutor_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
