# Generated by Django 5.1 on 2024-11-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0010_delete_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tipo_pet',
            field=models.CharField(choices=[('gato', 'Gato'), ('cachorro', 'Cachorro')], default='pet', max_length=50),
        ),
    ]
