# Generated by Django 5.1 on 2024-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0011_pet_tipo_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tipo',
            field=models.CharField(default='tipo_padrão', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.CharField(max_length=200),
        ),
    ]
