# Generated by Django 5.1 on 2024-11-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faund_app', '0013_remove_pet_tipo_alter_pet_tipo_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adotado',
            field=models.BooleanField(default=False),
        ),
    ]
